services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_MODEL=llama3
    depends_on:
      - ollama
    command: >
      sh -c "
        echo 'Waiting for Ollama to be ready...' &&
        sleep 20 &&
        echo 'Starting application...' &&
        uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama-data:/root/.ollama
    ports:
      - "11434:11434"

  chroma:
    image: chromadb/chroma:latest
    volumes:
      - chroma-data:/chroma/chroma
    ports:
      - "8001:8000"

volumes:
  chroma-data:
  ollama-data: 